#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_normal_color "#ECEFF4"
bspc config focused_border_color "#81A1C1"
#autostart
sxhkd &
nitrogen --restore &
picom &
dunst &
polybar &
xrandr --output Virtual1 --mode 1920x1080 &
xsetroot -cursor_name heart &
